[build]
builder = "nixpacks"
buildCommand = "pnpm nuxt:prepare && pnpm nuxt:build"

[deploy]
startCommand = "pnpm db:deploy && pnpm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
